name: generate_diann_cfg
description: A module to generate DIA-NN configure file.
keywords:
    - configure
    - DIA-NN
tools:
    - custom:
        description: |
            A custom module for DIA-NN configure file.
        homepage: https://github.com/bigbio/quantms
        documentation: https://github.com/bigbio/quantms/tree/readthedocs
input:
    - meta:
        type: map
        description: Groovy Map containing sample information
    - mzmls:
        type: dir
        description: mzML files directory
output:
    - library_config:
        type: file
        description: DIA-NN configure file for library generation
        pattern: "library_config.cfg"
    - search_cfg:
        type: file
        description: DIA-NN configure file for search and quantification
        pattern: "diann_config.cfg"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@Chengxin Dai"
