name: indexpeptides
description: Refreshes the protein references for all peptide hits from an idXML file and adds target/decoy information.
keywords:
    - decoy
    - PeptideIndexer
    - OpenMS
tools:
    - PeptideIndexer:
        description: |
          Refreshes the protein references for all peptide hits.
        homepage: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PeptideIndexer.html
        documentation: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PeptideIndexer.html
input:
    - mzml_id:
        type: value
        description: MD5
    - id_file:
        type: file
        description: |
          Input idXML file containing the identifications.
    - database:
        type: file
        description: |
          Input sequence database in FASTA format.
output:
    - mzml_id:
        type: value
        description: MD5
    - id_files_idx:
        type: file
        description: |
          Output idXML file.
    - log:
        type: file
        description: log file
        pattern: "*.log"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@daichengxin"
