name: thermorawfileparser
description: convert raw file to mzml files
keywords:
    - raw
    - mzML
    - fileparser
tools:
    - thermorawfileparser:
        description: |
            It takes a thermo RAW file as input and outputs indexed mzML
        homepage: https://github.com/compomics/ThermoRawFileParser
        documentation: https://github.com/compomics/ThermoRawFileParser
input:
    - mzml_id:
        type: map
        description: |
            Groovy Map containing sample information
    - rawfile:
        type: file
        description: |
          thermo RAW file
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - mzml:
        type: file
        description: indexed mzML
        pattern: "*.mzML"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@Chengxin Dai"
    - "@Yasset Perez-Riverol"
