name: extracpsmfeature
description:  Computes extra features for each input PSM.
keywords:
    - PSM
    - feature
    - OpenMS
tools:
    - PSMFeatureExtractor:
        description: |
          Computes extra features for each input PSM.
        homepage: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_PSMFeatureExtractor.html
        documentation: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_PSMFeatureExtractor.html
input:
    - mzml_id:
        type: value
        description: MD5
    - id_file:
        type: file
        description: |
          Input idXML file containing the identifications.
output:
    - mzml_id:
        type: value
        description: MD5
    - id_files_idx_feat:
        type: file
        description: |
          Output file in mzid or idXML format
    - log:
        type: file
        description: log file
        pattern: "*.log"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@daichengxin"
